[2025-10-25T19:24:19.028+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-25T19:24:19.075+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: energyzero_etl.generate_hourly_boxplot manual__2025-10-25T19:19:11.883400+00:00 [queued]>
[2025-10-25T19:24:19.084+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: energyzero_etl.generate_hourly_boxplot manual__2025-10-25T19:19:11.883400+00:00 [queued]>
[2025-10-25T19:24:19.085+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-10-25T19:24:19.100+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_hourly_boxplot> on 2025-10-25 19:19:11.883400+00:00
[2025-10-25T19:24:19.106+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=520) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-25T19:24:19.108+0000] {standard_task_runner.py:64} INFO - Started process 521 to run task
[2025-10-25T19:24:19.106+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'energyzero_etl', 'generate_hourly_boxplot', 'manual__2025-10-25T19:19:11.883400+00:00', '--job-id', '139', '--raw', '--subdir', 'DAGS_FOLDER/energyzero_dag.py', '--cfg-path', '/tmp/tmpgb1os1_i']
[2025-10-25T19:24:19.108+0000] {standard_task_runner.py:91} INFO - Job 139: Subtask generate_hourly_boxplot
[2025-10-25T19:24:19.136+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-25T19:24:19.209+0000] {task_command.py:426} INFO - Running <TaskInstance: energyzero_etl.generate_hourly_boxplot manual__2025-10-25T19:19:11.883400+00:00 [running]> on host 81dd241354df
[2025-10-25T19:24:19.355+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='energyzero_etl' AIRFLOW_CTX_TASK_ID='generate_hourly_boxplot' AIRFLOW_CTX_EXECUTION_DATE='2025-10-25T19:19:11.883400+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-25T19:19:11.883400+00:00'
[2025-10-25T19:24:19.355+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-25T19:24:20.216+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-25T19:24:20.217+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/energyzero_dag.py", line 38, in visualize_data
    subprocess.run(['python', script_path], check=True)
  File "/usr/local/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', '/opt/airflow/dags/../scripts/hourly_boxplot.py']' returned non-zero exit status 1.
[2025-10-25T19:24:20.244+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=energyzero_etl, task_id=generate_hourly_boxplot, run_id=manual__2025-10-25T19:19:11.883400+00:00, execution_date=20251025T191911, start_date=20251025T192419, end_date=20251025T192420
[2025-10-25T19:24:20.267+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 139 for task generate_hourly_boxplot (Command '['python', '/opt/airflow/dags/../scripts/hourly_boxplot.py']' returned non-zero exit status 1.; 521)
[2025-10-25T19:24:20.286+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-10-25T19:24:20.323+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-25T19:24:20.326+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
